@startuml component-diagram-n0-vacancy

title Diagrama de Componentes - N0 Vacancy

package "Frontend" {
    component "Interfaz de Usuario" as UI
interface "IU_Usuario" as UI_Interface
}

package "Backend" {
    component "Búsqueda" as Search
    component "Historial" as History
    component "Servidor" as Server
    component "Servicio de Autenticación" as Auth
    component "Notificaciones" as Notifications

interface "IBúsqueda" as Search_Interface
interface "IHistorial" as History_Interface
interface "IServidor" as Server_Interface
interface "IAutenticación" as Auth_Interface
interface "INotificaciones" as Notifications_Interface

}

database "Base de Datos" as DB


UI --> Server : Usa
Server --> DB : Usa
Server --> Auth : Usa
Server --> Notifications : Usa
Server --> Search : Usa
Server --> History : Usa

Search --> DB : Usa
History --> DB : Usa

UI ..> UI_Interface : Implementa
Server ..> Server_Interface : Implementa
Auth ..> Auth_Interface : Implementa
Notifications ..> Notifications_Interface : Implementa
Search ..> Search_Interface : Implementa
History ..> History_Interface : Implementa
@enduml
