@startuml product management

left to right direction
actor Administrador

rectangle "Product Management" {
  usecase "UC-12: Agregar producto" as UC12
  usecase "UC-13: Modificar producto" as UC13
  usecase "UC-14: Eliminar producto" as UC14
  usecase "UC-15: Modificar stock" as UC15
  usecase "UC-16: Recibir alerta de stock bajo" as UC16
}

Administrador --> UC12
Administrador --> UC13
Administrador --> UC14
Administrador --> UC15
Administrador --> UC16
@enduml